language: en-US
tone_instructions: "Be concise and focus on critical issues only"
reviews:
  profile: assertive
  commit_status: true
  high_level_summary: true
  path_filters:
    - "!node_modules/**"
    - "!dist/**"
    - "src/**"
  tools:
    eslint:
      enabled: true
    ruff:
      enabled: true
    gitleaks:
      enabled: true
  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - "wip"
      - "draft"
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/.cursorrules"
      - "**/CODING_STANDARDS.md"
